services:
  mysql:
    ports: []
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf

  minio:
    ports: []

  backend:
    ports: []

  frontend:
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/log/letsencrypt:/var/log/letsencrypt
